module.exports=function(sequelize,DataTypes){
    const CartItems=sequelize.define("CartItems",{
        name:{
            type:DataTypes.STRING,
            allowNull:false
        },
        productId:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        price:{
            type:DataTypes.DECIMAL(10,2),
            allowNull:false
        },
        availQty:{
            type:DataTypes.INTEGER
        },
        imageUrl:{
            type:DataTypes.STRING
        },
        department:{
            type:DataTypes.STRING,
            allowNull:false
        },
        buying:{
            type:DataTypes.INTEGER,
            allowNull:false
        }
    },
    {timestamps:false}
    );
    return CartItems;
};